version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    user: root
    ports: ["8080:8080"]
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jcasc:/var/jenkins_home/casc_configs
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml

  sonarqube:
    image: sonarqube:lts-community
    ports: ["9000:9000"]
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on: [postgres]
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nexus:
    image: sonatype/nexus3:3.68.1
    ports: ["8081:8081"]
    volumes:
      - nexus_data:/nexus-data

  registry:
    image: registry:2
    ports: ["5000:5000"]
    volumes:
      - registry_data:/var/lib/registry

volumes:
  jenkins_home: {}
  sonarqube_data: {}
  sonarqube_extensions: {}
  postgres_data: {}
  nexus_data: {}
  registry_data: {}
